const $=id=>document.getElementById(id),S=RESEARCH.summary,B=RESEARCH.board,T=RESEARCH.toronto;
const number=x=>Number(x).toLocaleString('en-CA'),signed=(v,d=2)=>(v>0?'+':'')+Number(v).toFixed(d),groups=['0 days','1 day','2 days','3+ days'];let page=0,filtered=[],selected,charts={};
const clubNames={TOR:'Toronto Blue Jays',ANA:'Los Angeles Angels',ARI:'Arizona Diamondbacks',ATL:'Atlanta Braves',BAL:'Baltimore Orioles',BOS:'Boston Red Sox',CHA:'Chicago White Sox',CHN:'Chicago Cubs',CIN:'Cincinnati Reds',CLE:'Cleveland Guardians',COL:'Colorado Rockies',DET:'Detroit Tigers',HOU:'Houston Astros',KCA:'Kansas City Royals',LAN:'Los Angeles Dodgers',MIA:'Miami Marlins',MIL:'Milwaukee Brewers',MIN:'Minnesota Twins',NYA:'New York Yankees',NYN:'New York Mets',ATH:'Athletics',OAK:'Athletics',PHI:'Philadelphia Phillies',PIT:'Pittsburgh Pirates',SDN:'San Diego Padres',SEA:'Seattle Mariners',SFN:'San Francisco Giants',SLN:'St. Louis Cardinals',TBA:'Tampa Bay Rays',TEX:'Texas Rangers',WAS:'Washington Nationals'};
for(const team of [...new Set(B.map(r=>r.team))].sort())$('team').add(new Option(clubNames[team]||team,team));$('team').value='TOR';
for(let m=3;m<=9;m++)$('month').add(new Option(new Date(2025,m-1,1).toLocaleDateString('en',{month:'long'}),String(m).padStart(2,'0')));
function pitcherOptions(){let old=$('pitcher').value;$('pitcher').innerHTML='<option value="all">All pitchers</option>';const names=new Map(B.filter(r=>r.team===$('team').value).map(r=>[r.id,r.name]));for(const [id,name]of [...names].sort((a,b)=>a[1].localeCompare(b[1])))$('pitcher').add(new Option(name,id));if(names.has(old))$('pitcher').value=old;}
function filter(){page=0;filtered=B.filter(r=>r.team===$('team').value&&($('month').value==='all'||r.dateISO.slice(5,7)===$('month').value)&&($('pitcher').value==='all'||r.id===$('pitcher').value)&&($('lens').value==='all'||$('lens').value==='b2b'&&r.rest===0||$('lens').value==='three'&&r.consecutive>=2||$('lens').value==='heavy'&&r.p1>=20)).sort((a,b)=>b.dateISO.localeCompare(a.dateISO)||a.name.localeCompare(b.name));selected=filtered[0];render();}
function usage(r){return r.consecutive>=2?'Both prior days':r.p1>=20?'20+ yesterday':r.rest===0?'Pitched yesterday':'No prior-day MLB use';}
function render(){const visible=filtered.slice(page*10,page*10+10);$('count').textContent=`${number(filtered.length)} ${filtered.length===1?'appearance':'appearances'} · ${new Set(filtered.map(r=>r.id)).size} ${new Set(filtered.map(r=>r.id)).size===1?'pitcher':'pitchers'}`;$('appearances').innerHTML=visible.length?visible.map(r=>`<tr class="${selected?.gid===r.gid&&selected?.id===r.id?'active':''}"><td>${r.dateISO.slice(5)}</td><td><button data-key="${r.gid}:${r.id}" aria-label="Inspect ${r.name}, ${r.dateISO}">${r.name}</button></td><td>${r.rest}</td><td>${r.p3}</td><td>${r.p7}</td><td><span class="usage ${r.rest?'quiet':''}">${usage(r)}</span></td></tr>`).join(''):'<tr><td colspan="6" class="empty">No eligible appearances match these filters. Try another month or workload lens.</td></tr>';$('previous').disabled=page===0;$('next').disabled=(page+1)*10>=filtered.length;$('page').textContent=filtered.length?`Page ${page+1} of ${Math.ceil(filtered.length/10)}`:'0 results';renderDetail();}
function renderDetail(){if(!selected){$('detail').innerHTML='<h3>No appearance selected</h3><p>Adjust the filters to explore the workload history.</p>';return;}const r=selected,max=Math.max(30,...r.prior7);$('detail').innerHTML=`<p class="eyebrow">APPEARANCE FILE / ${r.dateISO}</p><h3>${r.name}</h3><p>${r.team} vs ${r.opp} · entry inning ${r.entry}</p><div class="detail-stats"><div><strong>${r.rest}</strong><small>MLB off-days</small></div><div><strong>${r.p7}</strong><small>pitches / prior 7d</small></div></div><p class="eyebrow">RECORDED PITCHES BEFORE THIS DATE</p><div class="microbars">${r.prior7.map((v,i)=>`<div><b>${v}</b><i style="height:${v/max*65}px"></i><span>−${7-i}d</span></div>`).join('')}</div><p class="detail-note"><strong style="font-size:15px">${usage(r)}</strong>Review recent throwing with the player and staff. This flag does not establish fatigue or availability.</p><details><summary>Reveal observed outcome</summary><p class="outcome">${r.pitches} recorded pitches · ${r.p_bfp} batters faced · ${r.p_k} strikeouts · ${r.ubb} unintentional walks.<br>K−uBB rate: ${(r.y*100).toFixed(1)}%; prior baseline: ${(r.baseline*100).toFixed(1)}%.</p><p class="outcome">Outcomes are shown for retrospective evaluation and do not feed the workload flags.</p></details>`;}
$('appearances').addEventListener('click',e=>{const b=e.target.closest('button[data-key]');if(b){selected=filtered.find(r=>`${r.gid}:${r.id}`===b.dataset.key);render();}});
$('team').addEventListener('change',()=>{pitcherOptions();filter();});for(const id of ['month','pitcher','lens'])$(id).addEventListener('change',filter);$('previous').onclick=()=>{page--;selected=filtered[page*10];render();};$('next').onclick=()=>{page++;selected=filtered[page*10];render();};$('reset').onclick=()=>{$('team').value='TOR';$('month').value='all';$('lens').value='all';$('pitcher').value='all';pitcherOptions();filter();};pitcherOptions();filter();
for(const [id,val]of Object.entries({n:S.n,pitchersN:S.pitchers,trainN:S.trainN,testN:S.testN}))$(id).textContent=number(val);
const options={responsive:true,maintainAspectRatio:false,animation:false,plugins:{legend:{display:false}},scales:{x:{grid:{display:false},ticks:{color:'#53667b'}},y:{grid:{color:'#e1e7ed'},ticks:{color:'#53667b'}}}};
const uncertainty={id:'uncertainty',afterDatasetsDraw(chart){const ds=chart.data.datasets[0];if(!ds.bounds)return;const ctx=chart.ctx,meta=chart.getDatasetMeta(0),scale=chart.scales.y;ctx.save();ctx.strokeStyle='#172c43';ctx.lineWidth=1.5;ds.bounds.forEach((b,i)=>{const x=meta.data[i].x,lo=scale.getPixelForValue(b[0]),hi=scale.getPixelForValue(b[1]);ctx.beginPath();ctx.moveTo(x,lo);ctx.lineTo(x,hi);ctx.moveTo(x-5,lo);ctx.lineTo(x+5,lo);ctx.moveTo(x-5,hi);ctx.lineTo(x+5,hi);ctx.stroke();});ctx.restore();}};
function bar(id,labels,values,label,bounds){if(charts[id])charts[id].destroy();charts[id]=new Chart($(id),{type:'bar',data:{labels,datasets:[{label,data:values,bounds,backgroundColor:values.map(v=>v<0?'#6d8fa9':'#087e80'),maxBarThickness:60}]},plugins:[uncertainty],options:{...options,scales:{...options.scales,y:{...options.scales.y,suggestedMin:Math.min(0,...bounds.map(b=>b[0]))*1.15,suggestedMax:Math.max(0,...bounds.map(b=>b[1]))*1.15}},plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>label+': '+signed(c.raw)}}}}});}
function evidence(){const rows=S.strata.filter(r=>r.period===$('period').value);bar('restChart',rows.map(r=>r.rest),rows.map(r=>r.delta),'Δ K−uBB, pp',rows.map(r=>[r.lo,r.hi]));$('restRows').innerHTML=rows.map(r=>`<tr><td>${r.rest}</td><td>${number(r.n)}</td><td>${signed(r.delta)} pp</td><td>[${signed(r.lo)}, ${signed(r.hi)}]</td></tr>`).join('');}
const effectNames={b2b:'0 rest days vs. 3+',rest1:'1 rest day vs. 3+',rest2:'2 rest days vs. 3+',p3_10:'10 more pitches in prior 3 days',p7_10:'10 more pitches in prior 7 days',heavyYesterday:'20+ pitches yesterday',threeDays:'Pitched on both prior days'};
$('effects').innerHTML=S.coefficients.map(r=>`<div class="effect"><span>${effectNames[r.feature]}</span><b>${signed(r.estimate)} pp</b><small>95% interval [${signed(r.lo)}, ${signed(r.hi)}] pp</small></div>`).join('');$('period').onchange=evidence;evidence();
$('baseRmse').textContent=(S.models.context.rmse*100).toFixed(3);$('workRmse').textContent=(S.models.workload.rmse*100).toFixed(3);$('rmseDelta').textContent=signed(S.rmseDelta*100,3)+' pp';$('rmseCI').textContent=`95% paired-bootstrap interval: [${signed(S.rmseDeltaCI[0]*100,4)}, ${signed(S.rmseDeltaCI[1]*100,4)}] pp. The interval crosses zero.`;
function velocity(){const year=+$('velocityYear').value,rows=T.stats.filter(r=>r.year===year);bar('velocityChart',rows.map(r=>r.rest),rows.map(r=>r.delta),'Δ mph',rows.map(r=>[r.lo,r.hi]));$('velocityRows').innerHTML=rows.map(r=>`<tr><td>${r.rest}</td><td>${r.n} / ${r.pitchers}</td><td>${signed(r.delta)}</td><td>[${signed(r.lo)}, ${signed(r.hi)}]</td></tr>`).join('');const names=new Map(T.rows.filter(r=>r.year===year).map(r=>[r.id,r.name])),old=$('velocityPitcher').value;$('velocityPitcher').innerHTML='';for(const [id,name]of [...names].sort((a,b)=>a[1].localeCompare(b[1])))$('velocityPitcher').add(new Option(name,id));if(names.has(old))$('velocityPitcher').value=old;else if(names.has('romaj002'))$('velocityPitcher').value='romaj002';pitcherVelocity();}
function pitcherVelocity(){const rows=T.rows.filter(r=>r.year===+$('velocityYear').value&&r.id===$('velocityPitcher').value).sort((a,b)=>a.dateISO.localeCompare(b.dateISO));if(charts.pitcher)charts.pitcher.destroy();charts.pitcher=new Chart($('pitcherChart'),{type:'line',data:{labels:rows.map(r=>r.dateISO.slice(5)),datasets:[{label:'Δ four-seam velocity (mph)',data:rows.map(r=>r.deltaV),borderColor:'#075ca7',borderWidth:1.5,pointRadius:3,pointBackgroundColor:rows.map(r=>r.restGroup==='0 days'?'#aa6117':'#075ca7')}]},options:{...options,scales:{...options.scales,x:{...options.scales.x,ticks:{maxTicksLimit:6}}},plugins:{legend:{display:false},tooltip:{callbacks:{afterLabel:c=>`${rows[c.dataIndex].restGroup} rest · ${rows[c.dataIndex].ffN} measured FF`}}}}});$('velocitySummary').textContent=`${rows.length} qualifying appearances. Orange points: pitched the previous day. Velocity difference is relative to the prior qualifying-appearance average, not a season-end baseline.`;}
$('velocityYear').onchange=velocity;$('velocityPitcher').onchange=pitcherVelocity;velocity();$('sourceAudit').textContent=`Source audit: ${number(T.rawPitches)} Statcast rows across ${T.games} Toronto games; ${T.matchedAppearances} unambiguous pitcher-date matches. Recorded pitch counts match exactly in ${T.pitchCountExact} (${(100*T.pitchCountExact/T.matchedAppearances).toFixed(1)}%) and within two in ${T.pitchCountWithin2}. Feed differences remain; the velocity sample contains ${T.eligible} eligible appearances. Intervals use 1,000 pitcher-cluster resamples.`;
$('exclusions').textContent=`Overlapping exclusion counts among raw relief appearances: ${S.excluded.suspendedRelief} suspended-game appearances; ${S.excluded.sameDayDoubleRelief} appearances on two-appearance pitcher-days; ${S.excluded.insufficientPriorRelief} with fewer than five earlier relief appearances; ${S.excluded.nonPitcherRoleRelief} outside the pitcher-majority role cohort. These counts overlap and should not be added.`;
if(document.modelContext?.registerTool)Promise.resolve(document.modelContext.registerTool({name:'read_bullpen_view',description:'Read the current historical bullpen filters, selected appearance and held-out model result. Does not judge medical fatigue or roster availability.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected empty object');return {filters:{team:$('team').value,month:$('month').value,pitcher:$('pitcher').value,lens:$('lens').value},matches:filtered.length,selected:selected||null,test:{rmseDelta:S.rmseDelta,interval:S.rmseDeltaCI}};}})).catch(()=>{});
