const $=id=>document.getElementById(id),S=RESEARCH.summary,B=RESEARCH.board,T=RESEARCH.toronto,D=RESEARCH.diagnostics;
const number=x=>Number(x).toLocaleString('en-CA'),signed=(v,d=2)=>(v>0?'+':'')+Number(v).toFixed(d),groups=['0 days','1 day','2 days','3+ days'];let page=0,filtered=[],selected,charts={},restoring=true;const initialParams=new URLSearchParams(location.search);
const clubNames={TOR:'Toronto Blue Jays',ANA:'Los Angeles Angels',ARI:'Arizona Diamondbacks',ATL:'Atlanta Braves',BAL:'Baltimore Orioles',BOS:'Boston Red Sox',CHA:'Chicago White Sox',CHN:'Chicago Cubs',CIN:'Cincinnati Reds',CLE:'Cleveland Guardians',COL:'Colorado Rockies',DET:'Detroit Tigers',HOU:'Houston Astros',KCA:'Kansas City Royals',LAN:'Los Angeles Dodgers',MIA:'Miami Marlins',MIL:'Milwaukee Brewers',MIN:'Minnesota Twins',NYA:'New York Yankees',NYN:'New York Mets',ATH:'Athletics',OAK:'Athletics',PHI:'Philadelphia Phillies',PIT:'Pittsburgh Pirates',SDN:'San Diego Padres',SEA:'Seattle Mariners',SFN:'San Francisco Giants',SLN:'St. Louis Cardinals',TBA:'Tampa Bay Rays',TEX:'Texas Rangers',WAS:'Washington Nationals'};
for(const team of [...new Set(B.map(r=>r.team))].sort())$('team').add(new Option(clubNames[team]||team,team));$('team').value='TOR';
for(let m=3;m<=9;m++)$('month').add(new Option(new Date(2025,m-1,1).toLocaleDateString('en',{month:'long'}),String(m).padStart(2,'0')));
function pitcherOptions(){let old=$('pitcher').value;$('pitcher').innerHTML='<option value="all">All pitchers</option>';const names=new Map(B.filter(r=>r.team===$('team').value).map(r=>[r.id,r.name]));for(const [id,name]of [...names].sort((a,b)=>a[1].localeCompare(b[1])))$('pitcher').add(new Option(name,id));if(names.has(old))$('pitcher').value=old;}
function filter(){page=0;filtered=B.filter(r=>r.team===$('team').value&&r.dateISO<=$('asof').value&&($('month').value==='all'||r.dateISO.slice(5,7)===$('month').value)&&($('pitcher').value==='all'||r.id===$('pitcher').value)&&($('lens').value==='all'||$('lens').value==='b2b'&&r.rest===0||$('lens').value==='three'&&r.consecutive>=2||$('lens').value==='heavy'&&r.p1>=20)).sort((a,b)=>b.dateISO.localeCompare(a.dateISO)||a.name.localeCompare(b.name));selected=filtered[0];render();}
function usage(r){return r.consecutive>=2?'Both prior days':r.p1>=20?'20+ yesterday':r.rest===0?'Pitched yesterday':'No prior-day MLB use';}
function render(){const visible=filtered.slice(page*10,page*10+10);$('count').textContent=`${number(filtered.length)} ${filtered.length===1?'appearance':'appearances'} · ${new Set(filtered.map(r=>r.id)).size} ${new Set(filtered.map(r=>r.id)).size===1?'pitcher':'pitchers'}`;$('appearances').innerHTML=visible.length?visible.map(r=>`<tr class="${selected?.gid===r.gid&&selected?.id===r.id?'active':''}"><td>${r.dateISO.slice(5)}</td><td><button data-key="${r.gid}:${r.id}" aria-pressed="${selected?.gid===r.gid&&selected?.id===r.id}" aria-label="Inspect ${r.name}, ${r.dateISO}">${r.name}</button></td><td>${r.rest}</td><td>${r.p3}</td><td>${r.p7}</td><td><span class="usage ${r.rest?'quiet':''}">${usage(r)}</span></td></tr>`).join(''):'<tr><td colspan="6" class="empty">No eligible appearances match these filters. Try another month or workload lens.</td></tr>';$('previous').disabled=page===0;$('next').disabled=(page+1)*10>=filtered.length;$('page').textContent=filtered.length?`Page ${page+1} of ${Math.ceil(filtered.length/10)}`:'0 results';renderDetail();renderDossier();persistView();}
function renderDetail(){if(!selected){$('detail').innerHTML='<h3>No appearance selected</h3><p>Adjust the filters to explore the workload history.</p>';return;}const r=selected,max=Math.max(30,...r.prior7);$('detail').innerHTML=`<p class="eyebrow">APPEARANCE FILE / ${r.dateISO}</p><h3>${r.name}</h3><p>${r.team} vs ${r.opp} · entry inning ${r.entry}</p>${r.rest>=14?'<span class="gap-badge">Long MLB gap · recovery context missing</span>':''}<div class="detail-stats"><div><strong>${r.rest}</strong><small>MLB off-days</small></div><div><strong>${r.p7}</strong><small>pitches / prior 7d</small></div></div><p class="eyebrow">RECORDED PITCHES BEFORE THIS DATE</p><div class="microbars">${r.prior7.map((v,i)=>`<div><b>${v}</b><i style="height:${v/max*65}px"></i><span>−${7-i}d</span></div>`).join('')}</div><a class="dossier-link" href="#dossier">Open pitcher dossier ↓</a><p class="detail-note"><strong style="font-size:15px">${usage(r)}</strong>Review recent throwing with the player and staff. This flag does not establish fatigue or availability.</p><details><summary>Reveal observed outcome</summary><p class="outcome">${r.pitches} recorded pitches · ${r.p_bfp} batters faced · ${r.p_k} strikeouts · ${r.ubb} unintentional walks.<br>K−uBB rate: ${(r.y*100).toFixed(1)}%; prior baseline: ${(r.baseline*100).toFixed(1)}%.</p><p class="outcome">Outcomes are shown for retrospective evaluation and do not feed the workload flags.</p></details>`;}
$('appearances').addEventListener('click',e=>{const b=e.target.closest('button[data-key]');if(b){selected=filtered.find(r=>`${r.gid}:${r.id}`===b.dataset.key);render();}});
$('team').addEventListener('change',()=>{pitcherOptions();filter();});for(const id of ['month','pitcher','lens'])$(id).addEventListener('change',filter);$('previous').onclick=()=>{page--;selected=filtered[page*10];render();};$('next').onclick=()=>{page++;selected=filtered[page*10];render();};$('reset').onclick=()=>{$('asof').value='2025-09-28';$('team').value='TOR';$('month').value='all';$('lens').value='all';$('pitcher').value='all';pitcherOptions();filter();};
for(const [id,val]of Object.entries({n:S.n,pitchersN:S.pitchers,trainN:S.trainN,testN:S.testN}))$(id).textContent=number(val);
const options={responsive:true,maintainAspectRatio:false,animation:false,plugins:{legend:{display:false}},scales:{x:{grid:{display:false},ticks:{color:'#53667b'}},y:{grid:{color:'#e1e7ed'},ticks:{color:'#53667b'}}}};
const uncertainty={id:'uncertainty',afterDatasetsDraw(chart){const ds=chart.data.datasets[0];if(!ds.bounds)return;const ctx=chart.ctx,meta=chart.getDatasetMeta(0),scale=chart.scales.y;ctx.save();ctx.strokeStyle='#172c43';ctx.lineWidth=1.5;ds.bounds.forEach((b,i)=>{const x=meta.data[i].x,lo=scale.getPixelForValue(b[0]),hi=scale.getPixelForValue(b[1]);ctx.beginPath();ctx.moveTo(x,lo);ctx.lineTo(x,hi);ctx.moveTo(x-5,lo);ctx.lineTo(x+5,lo);ctx.moveTo(x-5,hi);ctx.lineTo(x+5,hi);ctx.stroke();});ctx.restore();}};
function bar(id,labels,values,label,bounds){if(charts[id])charts[id].destroy();charts[id]=new Chart($(id),{type:'bar',data:{labels,datasets:[{label,data:values,bounds,backgroundColor:values.map(v=>v<0?'#6d8fa9':'#087e80'),maxBarThickness:60}]},plugins:[uncertainty],options:{...options,scales:{...options.scales,y:{...options.scales.y,suggestedMin:Math.min(0,...bounds.map(b=>b[0]))*1.15,suggestedMax:Math.max(0,...bounds.map(b=>b[1]))*1.15}},plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>label+': '+signed(c.raw)}}}}});}
function evidence(){const rows=S.strata.filter(r=>r.period===$('period').value);bar('restChart',rows.map(r=>r.rest),rows.map(r=>r.delta),'Δ K−uBB, pp',rows.map(r=>[r.lo,r.hi]));$('restRows').innerHTML=rows.map(r=>`<tr><td>${r.rest}</td><td>${number(r.n)}</td><td>${signed(r.delta)} pp</td><td>[${signed(r.lo)}, ${signed(r.hi)}]</td></tr>`).join('');}
const effectNames={b2b:'0 rest days vs. 3+',rest1:'1 rest day vs. 3+',rest2:'2 rest days vs. 3+',p3_10:'10 more pitches in prior 3 days',p7_10:'10 more pitches in prior 7 days',heavyYesterday:'20+ pitches yesterday',threeDays:'Pitched on both prior days'};
$('effects').innerHTML=S.coefficients.map(r=>`<div class="effect"><span>${effectNames[r.feature]}</span><b>${signed(r.estimate)} pp</b><small>95% interval [${signed(r.lo)}, ${signed(r.hi)}] pp</small></div>`).join('');$('period').onchange=evidence;evidence();
$('baseRmse').textContent=(S.models.context.rmse*100).toFixed(3);$('workRmse').textContent=(S.models.workload.rmse*100).toFixed(3);$('rmseDelta').textContent=signed(S.rmseDelta*100,3)+' pp';$('rmseCI').textContent=`95% paired-bootstrap interval: [${signed(S.rmseDeltaCI[0]*100,4)}, ${signed(S.rmseDeltaCI[1]*100,4)}] pp. The interval crosses zero.`;
function velocity(){const year=+$('velocityYear').value,rows=T.stats.filter(r=>r.year===year);bar('velocityChart',rows.map(r=>r.rest),rows.map(r=>r.delta),'Δ mph',rows.map(r=>[r.lo,r.hi]));$('velocityRows').innerHTML=rows.map(r=>`<tr><td>${r.rest}</td><td>${r.n} / ${r.pitchers}</td><td>${signed(r.delta)}</td><td>[${signed(r.lo)}, ${signed(r.hi)}]</td></tr>`).join('');const names=new Map(T.rows.filter(r=>r.year===year).map(r=>[r.id,r.name])),old=$('velocityPitcher').value;$('velocityPitcher').innerHTML='';for(const [id,name]of [...names].sort((a,b)=>a[1].localeCompare(b[1])))$('velocityPitcher').add(new Option(name,id));if(names.has(old))$('velocityPitcher').value=old;else if(names.has('romaj002'))$('velocityPitcher').value='romaj002';pitcherVelocity();}
function pitcherVelocity(){const rows=T.rows.filter(r=>r.year===+$('velocityYear').value&&r.id===$('velocityPitcher').value).sort((a,b)=>a.dateISO.localeCompare(b.dateISO));if(charts.pitcher)charts.pitcher.destroy();charts.pitcher=new Chart($('pitcherChart'),{type:'line',data:{labels:rows.map(r=>r.dateISO.slice(5)),datasets:[{label:'Δ four-seam velocity (mph)',data:rows.map(r=>r.deltaV),borderColor:'#075ca7',borderWidth:1.5,pointRadius:3,pointBackgroundColor:rows.map(r=>r.restGroup==='0 days'?'#aa6117':'#075ca7')}]},options:{...options,scales:{...options.scales,x:{...options.scales.x,ticks:{maxTicksLimit:6}}},plugins:{legend:{display:false},tooltip:{callbacks:{afterLabel:c=>`${rows[c.dataIndex].restGroup} rest · ${rows[c.dataIndex].ffN} measured FF`}}}}});$('velocitySummary').textContent=`${rows.length} qualifying appearances. Orange points: pitched the previous day. Velocity difference is relative to the prior qualifying-appearance average, not a season-end baseline.`;}
$('velocityYear').onchange=velocity;$('velocityPitcher').onchange=pitcherVelocity;velocity();$('sourceAudit').textContent=`Source audit: ${number(T.rawPitches)} Statcast rows across ${T.games} Toronto games; ${T.matchedAppearances} unambiguous pitcher-date matches. Recorded pitch counts match exactly in ${T.pitchCountExact} (${(100*T.pitchCountExact/T.matchedAppearances).toFixed(1)}%) and within two in ${T.pitchCountWithin2}. Feed differences remain; the velocity sample contains ${T.eligible} eligible appearances. Intervals use 1,000 pitcher-cluster resamples.`;
$('exclusions').textContent=`Overlapping exclusion counts among raw relief appearances: ${S.excluded.suspendedRelief} suspended-game appearances; ${S.excluded.sameDayDoubleRelief} appearances on two-appearance pitcher-days; ${S.excluded.insufficientPriorRelief} with fewer than five earlier relief appearances; ${S.excluded.nonPitcherRoleRelief} outside the pitcher-majority role cohort. These counts overlap and should not be added.`;
if(document.modelContext?.registerTool)Promise.resolve(document.modelContext.registerTool({name:'read_bullpen_view',description:'Read the current historical bullpen filters, selected appearance and held-out model result. Does not judge medical fatigue or roster availability.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected empty object');return {filters:{asof:$('asof').value,team:$('team').value,month:$('month').value,pitcher:$('pitcher').value,lens:$('lens').value},matches:filtered.length,selected:selected||null,test:{rmseDelta:S.rmseDelta,interval:S.rmseDeltaCI}};}})).catch(()=>{});

// The dossier contains strictly earlier dated workload and earlier eligible outcomes.
function dateShift(date,days){const d=new Date(date+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10);}
function renderDossier(){
 const r=selected;$('dossierContent').hidden=!r;$('dossierEmpty').hidden=!!r;
 if(!r){$('dossierName').textContent='No appearance selected';$('dossierContext').textContent='Choose another filter combination to inspect a pitcher’s history.';$('dossierEmpty').textContent='No eligible appearance matches the current view.';return;}
 $('dossierName').textContent=r.name;$('dossierContext').textContent=`Before ${r.dateISO} · ${clubNames[r.team]||r.team} vs ${r.opp}. Every date in this dossier precedes that appearance.`;
 const allHistory=D.histories[r.id]||[],historyMap=new Map(allHistory),start=dateShift(r.dateISO,-42),daily=[];
 for(let d=start;d<r.dateISO;d=dateShift(d,1)){if(d>='2025-03-18')daily.push({date:d,pitches:historyMap.get(d)||0});}
 const earlier=B.filter(a=>a.id===r.id&&a.dateISO<r.dateISO).sort((a,b)=>a.dateISO.localeCompare(b.dateISO)),prior10=earlier.slice(-10),percentile=earlier.length>=10?100*earlier.filter(a=>a.p7<=r.p7).length/earlier.length:null;
 const total=daily.reduce((s,a)=>s+a.pitches,0),bf=prior10.reduce((s,a)=>s+a.p_bfp,0),net=prior10.reduce((s,a)=>s+a.p_k-a.ubb,0);
 $('dossierStats').innerHTML=`<div><strong>${r.p7}</strong><span>pitches in the prior 7 dates</span><small>All recorded MLB pitching</small></div><div><strong>${percentile===null?'—':Math.round(percentile)+'%'}</strong><span>of earlier outings at or below this 7d load</span><small>${earlier.length} earlier eligible appearances${percentile===null?' · at least 10 needed':''}</small></div><div><strong>${total}</strong><span>recorded pitches over ${daily.length} prior dates</span><small>Includes starts and other clubs</small></div><div><strong>${bf?(net/bf*100).toFixed(1)+'%':'—'}</strong><span>K−uBB rate over ${prior10.length} earlier eligible outings</span><small>${bf} total batters faced</small></div>`;
 if(charts.history)charts.history.destroy();charts.history=new Chart($('historyChart'),{type:'bar',data:{labels:daily.map(a=>a.date.slice(5)),datasets:[{label:'Recorded MLB pitches',data:daily.map(a=>a.pitches),backgroundColor:daily.map(a=>a.date>=dateShift(r.dateISO,-7)?'#075ca7':'#8fabbf'),maxBarThickness:15}]},options:{...options,scales:{x:{grid:{display:false},ticks:{maxTicksLimit:7,color:'#53667b'}},y:{beginAtZero:true,grid:{color:'#e1e7ed'},ticks:{color:'#53667b'}}}}});
 $('historyRows').innerHTML=daily.slice().reverse().map(a=>`<tr><td>${a.date}</td><td>${a.pitches}</td></tr>`).join('');
 const previous=allHistory.filter(a=>a[0]<r.dateISO).at(-1);
 let notes=`<div class="review-item${r.rest>=14?' gap':''}"><strong>${r.rest>=14?'A long gap is not confirmed recovery.':'Establish the actual throwing history.'}</strong><p>Last recorded MLB pitching date: ${previous?previous[0]:'not available'}. ${r.rest} full calendar days without an MLB appearance. Minor-league, rehab and bullpen throwing are not in this record.</p></div>`;
 notes+=`<div class="review-item"><strong>${r.consecutive>=2?'Used on both previous dates.':r.p1>=20?'A heavier previous-day outing.':r.rest===0?'A return on the following day.':'Check the planned role and game context.'}</strong><p>${r.p1} recorded pitches yesterday; ${r.p3} over the prior three dates. These are factual usage descriptors, not estimated fatigue levels.</p></div>`;
 notes+=`<div class="review-item"><strong>${percentile===null?'Limited personal comparison.':'Compare with his own usage pattern.'}</strong><p>${percentile===null?'Fewer than ten earlier eligible appearances are available for a workload percentile.':`${Math.round(percentile)}% of this pitcher’s ${earlier.length} earlier eligible appearances had an equal or lower seven-day pitch total. This is a historical rank, not a performance prediction.`}</p></div>`;
 $('dossierNotes').innerHTML=notes;
 const velocityEarlier=T.rows.filter(a=>a.id===r.id&&a.year===2025&&a.dateISO<r.dateISO).sort((a,b)=>a.dateISO.localeCompare(b.dateISO)),latest=velocityEarlier.at(-1);
 $('dossierVelocity').innerHTML=latest?`<strong>Latest earlier qualifying Toronto four-seam reading</strong><p>${latest.dateISO}: ${latest.velocity.toFixed(1)} mph over ${latest.ffN} measured four-seams; ${signed(latest.deltaV)} mph versus its trailing baseline. This is an earlier observation, not an estimate for ${r.dateISO}.</p><a href="#toronto">Inspect Toronto velocity evidence ↗</a>`:'<strong>No earlier qualifying Toronto four-seam reading in this sample.</strong><p>The velocity supplement covers Toronto only and applies a minimum-pitch rule. Missing here does not mean a pitcher lacks a fastball or has no tracking data elsewhere.</p>';
 $('priorRows').innerHTML=prior10.length?prior10.slice().reverse().map(a=>`<tr><td>${a.dateISO}</td><td>${a.team}</td><td>${a.rest}</td><td>${a.p7}</td><td>${a.pitches}</td><td>${a.p_bfp}</td><td>${a.p_k}</td><td>${a.ubb}</td><td>${(a.y*100).toFixed(1)}%</td></tr>`).join(''):'<tr><td colspan="9">No earlier eligible appearances in the 2025 board. The daily chart may still show pitching outside the research cohort.</td></tr>';
}
function persistView(){if(restoring)return;const url=new URL(location.href);for(const id of ['team','month','pitcher','lens','asof'])url.searchParams.set(id,$(id).value);if(selected)url.searchParams.set('appearance',selected.gid+':'+selected.id);else url.searchParams.delete('appearance');try{history.replaceState(null,'',url);}catch{/* Some file preview hosts disallow URL updates. */}$('shareStatus').textContent='';}
$('asof').addEventListener('change',()=>{if(!$('asof').value||$('asof').value<'2025-03-18'||$('asof').value>'2025-09-28')$('asof').value='2025-09-28';filter();});
$('copyLink').onclick=async()=>{persistView();try{await navigator.clipboard.writeText(location.href);$('shareStatus').textContent=location.protocol==='file:'||['localhost','127.0.0.1'].includes(location.hostname)?'Local preview link copied. Use your published site URL to share externally.':'View link copied.';}catch{$('shareStatus').textContent='Copy this address: '+location.href;}};
$('exportView').onclick=()=>{const keys=['dateISO','name','team','opp','rest','p1','p3','p7','pitches','p_bfp','p_k','ubb','y'];const escape=v=>'"'+String(v).replaceAll('"','""')+'"';const csv=[keys.join(','),...filtered.map(r=>keys.map(k=>escape(r[k])).join(','))].join('\r\n');const a=document.createElement('a'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));a.href=url;a.download=`bullpen-${$('team').value}-through-${$('asof').value}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('shareStatus').textContent=`Exported ${filtered.length} appearances. Includes observed outcomes for retrospective review.`;};
function diagnostics(){
 $('robustnessRows').innerHTML=D.checks.map(r=>`<tr><td><strong>${r.label}</strong><small>${r.definition}</small></td><td>${number(r.n)} / ${r.pitchers}</td><td>${r.context.toFixed(3)}</td><td>${r.workload.toFixed(3)}</td><td><b>${signed(r.delta,3)} pp</b><small>[${signed(r.lo,3)}, ${signed(r.hi,3)}]</small></td></tr>`).join('');
 const naive=D.checks[0].naive,context=D.checks[0].context,skill=100*(1-context*context/(naive*naive));
 $('benchmark').innerHTML=`<strong>A useful reference point:</strong> Predicting the same development-sample league rate (${D.naiveRate.toFixed(2)}%) for every appearance produces a ${naive.toFixed(3)} pp RMSE. The context model reduces mean squared error by ${skill.toFixed(2)}% versus that simple benchmark. Workload’s incremental value is the separate comparison above.`;
 $('gapAudit').textContent=`${number(D.longGaps)} held-out appearances follow 14+ MLB off-days. That gap may include throwing we cannot see. The “No long MLB gaps” diagnostic separately restricts evaluation to 0–6 off-days; neither cutoff is a medical standard.`;
 bar('monthChart',D.monthly.map(r=>r.label),D.monthly.map(r=>r.delta),'RMSE change, pp',D.monthly.map(r=>[r.lo,r.hi]));
 $('monthRows').innerHTML=D.monthly.map(r=>`<tr><td>${r.label}</td><td>${number(r.n)}</td><td>${signed(r.delta,3)}</td><td>[${signed(r.lo,3)}, ${signed(r.hi,3)}]</td></tr>`).join('');
 $('qualityRows').innerHTML=D.torontoQuality.map(r=>`<tr><td>${r.year}</td><td>${r.label}</td><td>${r.n} / ${r.pitchers}</td><td>${signed(r.delta,3)} mph</td></tr>`).join('');
}
function setSelect(id,value){if(value&&Array.from($(id).options).some(o=>o.value===value))$(id).value=value;}
setSelect('team',initialParams.get('team'));pitcherOptions();for(const id of ['month','pitcher','lens'])setSelect(id,initialParams.get(id));const savedDate=initialParams.get('asof');if(savedDate&&/^2025-\d\d-\d\d$/.test(savedDate)&&savedDate>='2025-03-18'&&savedDate<='2025-09-28'){$('asof').value=savedDate;if(!$('asof').value)$('asof').value='2025-09-28';}
filter();const savedAppearance=initialParams.get('appearance');if(savedAppearance){const i=filtered.findIndex(r=>r.gid+':'+r.id===savedAppearance);if(i>=0){selected=filtered[i];page=Math.floor(i/10);render();}}restoring=false;diagnostics();
